# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log into registry ${{ secrets.DOCKER_HUB }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ secrets.DOCKER_HUB }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta_app
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_HUB }}/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_app.outputs.tags }}
          labels: ${{ steps.meta_app.outputs.labels }}
          target: app
      - uses: shrink/actions-docker-extract@v1
        id: extract
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        with:
          image: ${{ secrets.DOCKER_HUB }}/${{ github.repository }}
          path: /usr/share/nginx/html/demo
      - name: Upload Dist
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: dist
      - name: Deploy 🚀
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          repository-name	: verified-run/demo
          branch: main
          folder: ${{ steps.extract.outputs.destination }}/demo
